#!/usr/bin/env bash
# Deploy static frontend to the S3 website bucket.
# Generates gitignored config.js from Terraform output, then syncs assets.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="${ROOT_DIR}/terraform"
FRONTEND_DIR="${ROOT_DIR}/frontend"

cd "${TF_DIR}"

MOVERS_URL="$(terraform output -raw movers_url)"
BUCKET="$(terraform output -raw frontend_bucket_name)"
WEBSITE_URL="$(terraform output -raw s3_website_url)"

# Inject live API URL — never commit this file (see .gitignore).
cat > "${FRONTEND_DIR}/config.js" <<EOF
// Generated by scripts/deploy_frontend.sh — do not edit or commit.
window.API_URL = "${MOVERS_URL}";
EOF

aws s3 sync "${FRONTEND_DIR}/" "s3://${BUCKET}/" \
  --delete \
  --exclude "config.js.example" \
  --exclude ".DS_Store"

echo "Deployed frontend to ${WEBSITE_URL}"
echo "Open that URL and confirm the table loads (Network tab → GET /movers, no CORS errors)."
